version: '3.1'

services:
  backend-python:
    build:
      context: ./backend/python
    ports:
      - 5000:5000
    command: "python3.8 server.py"
    container_name: wop_backend_python
    networks:
      - wop-network
  backend-nodejs:
    build:
      context: ./backend/nodejs
    ports:
      - 8080:8080
    command: "npm run start"
    environment:
      - PYTHON_SERVER=http://wop_backend_python:5000
    depends_on:
      - backend-python
    container_name: wop_backend_nodejs 
    networks:
      - wop-network
networks:
  wop-network:
    driver: bridge
    ipam:
      driver: default
